### ISSUE TITLE
AppService namespace conflict: non-exclusive wide regex breaks other appservices (double puppeting registration)

### ISSUE THREAD

**Issue by meovary150** [matrix-construct/tuwunel#72]
### Summary

When registering an additional AppService for automatic double-puppeting, following the official [[mautrix double-puppeting guide](https://docs.mau.fi/bridges/general/double-puppeting.html#automatic-double-puppeting)](https://docs.mau.fi/bridges/general/double-puppeting.html#automatic-double-puppeting), using a wide user namespace regex with `exclusive: false` (such as `@.*:localhost`) will cause existing appservices (e.g. mautrix-whatsapp) to receive `M_FORBIDDEN` errors and lose access to their user namespaces. This breaks bridge connectivity, even though `exclusive: false` is intended to allow namespace overlaps according to the [[Matrix AppService specification](https://spec.matrix.org/v1.11/application-service-api/#namespaces)](https://spec.matrix.org/v1.11/application-service-api/#namespaces).

------

### Steps to Reproduce

1. Set up a working Tuwunel homeserver and a working appservice (e.g., mautrix-whatsapp) with the following user namespace:

   ```yaml
   namespaces:
     users:
       - regex: "^@whatsapp_.*:localhost$"
         exclusive: true
   ```

2. Register an additional appservice (for double-puppeting) with a wide namespace:

   ```yaml
   id: doublepuppet
   url: null
   as_token: (random)
   hs_token: (random)
   sender_localpart: doublepuppetbot
   rate_limited: false
   namespaces:
     users:
       - regex: "@.*:localhost"
         exclusive: false
   ```

3. After registration, restart the homeserver and bridge.

4. Observe that mautrix-whatsapp and other appservices now fail all `/ping` requests with:

   ```
   M_FORBIDDEN (HTTP 403): M_FORBIDDEN: Appservices can only ping themselves (wrong appservice ID)
   ```

5. Unregister the wide-namespace double-puppet appservice, then restart. All bridges function normally again.

------

### Expected Behavior

Appservices with `exclusive: false` and overlapping namespaces should **not** block or override other appservices' access to their namespaces, as per the Matrix spec.
 Multiple appservices should be able to share non-exclusive namespaces without interfering with each other's authentication and routing.

------

### Actual Behavior

Registering a wide non-exclusive user namespace causes all relevant user_ids to be attributed only to the most recently registered appservice, blocking previous bridges from functioning (all requests get `403 M_FORBIDDEN`).

------

### References

- [[Matrix AppService Spec: Namespaces](https://spec.matrix.org/v1.11/application-service-api/#namespaces)](https://spec.matrix.org/v1.11/application-service-api/#namespaces)
- [[mautrix Automatic Double Puppeting Guide](https://docs.mau.fi/bridges/general/double-puppeting.html#automatic-double-puppeting)](https://docs.mau.fi/bridges/general/double-puppeting.html#automatic-double-puppeting)

------

### Suggested Resolution

Please review the namespace routing logic for appservices in Tuwunel to ensure it complies with the Matrix spec regarding overlapping non-exclusive namespaces, and allows multiple appservices to coexist as described in the spec and mautrix documentation.
